Update update-initramfs

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -9,49 +9,49 @@
 
 set -e
 
-if [ ! -e /usr/sbin/update-initramfs.orig.initramfs-tools ]
-then
-	echo "E: /usr/sbin/update-initramfs.orig.initramfs-tools - command not found"
-	echo "E: On Debian based systems, update-initramfs from initramfs-tools"
-	echo "E: can be installed with:"
-	echo "E:   apt-get install initramfs-tools"
-
-	exit 1
-fi
+#if [ ! -e /usr/sbin/update-initramfs.orig.initramfs-tools ]
+#then
+#	echo "E: /usr/sbin/update-initramfs.orig.initramfs-tools - command not found"
+#	echo "E: On Debian based systems, update-initramfs from initramfs-tools"
+#	echo "E: can be installed with:"
+#	echo "E:   apt-get install initramfs-tools"
+#
+#	exit 1
+#fi
 
 # system is a live system and not a system in the process of being built by live-build
-if [ ! -e /.live-build ] && grep -qs "boot=live" /proc/cmdline
-then
-	if grep -qs "\/run\/live\/medium" /proc/mounts
-	then
-		# live system with live media mounted as /run/live/medium
-		_DEVICE="$(awk '/\/run\/live\/medium/ { print $1 }' /proc/mounts)"
-
-		mount -o remount,rw ${_DEVICE} > /dev/null 2>&1 || true
-
-		if touch /run/live/medium/.test > /dev/null 2>&1
-		then
-			_READ_WRITE="true"
-
-			rm -f /run/live/medium/.test
-		else
-			_READ_WRITE="false"
-		fi
-	else
+#if [ ! -e /.live-build ] && grep -qs "boot=live" /proc/cmdline
+#then
+#	if grep -qs "\/run\/live\/medium" /proc/mounts
+#	then
+#		# live system with live media mounted as /run/live/medium
+#		_DEVICE="$(awk '/\/run\/live\/medium/ { print $1 }' /proc/mounts)"
+#
+#		mount -o remount,rw ${_DEVICE} > /dev/null 2>&1 || true
+#
+#		if touch /run/live/medium/.test > /dev/null 2>&1
+#		then
+#			_READ_WRITE="true"
+#
+#			rm -f /run/live/medium/.test
+#		else
+#			_READ_WRITE="false"
+#		fi
+#	else
 		# live system without live media mounted as /run/live/medium
-		echo "I: update-initramfs is disabled (live system is running without media mounted on /run/live/medium)."
+#		echo "I: update-initramfs is disabled (live system is running without media mounted on /run/live/medium)."
 
-		exit 0
-	fi
-else
+#		exit 0
+#	fi
+#else
 	# non-live system
 	/usr/sbin/update-initramfs.orig.initramfs-tools "${@}"
 
 	exit "${?}"
-fi
+#fi
 
-case "${_READ_WRITE}" in
-	true)
+#case "${_READ_WRITE}" in
+#	true)
 		# Updating initramfs
 		/usr/sbin/update-initramfs.orig.initramfs-tools "${@}"
 
@@ -87,8 +87,8 @@ case "${_READ_WRITE}" in
 		done
 		;;
 
-	false)
-		echo "I: update-initramfs is disabled (live system is running on read-only media)."
-		exit 0
-		;;
-esac
+	#false)
+	#	echo "I: update-initramfs is disabled (live system is running on read-only media)."
+	#	exit 0
+	#	;;
+#esac
